<div class="mdc-typography--headline5">
    <p>Rapid Fire Questions<p>
</div>

<div class="mdc-typography--body1">
    <DataTable table$aria-label="People list" style="max-width: 100%;">
        <Head>
            <Row>
                <Cell>Question</Cell>
                <Cell>Answer</Cell>
            </Row>
            </Head>
        <Body>
            <Row>
                <Cell>趣味</Cell>
                <Cell>プログラミング</Cell>
            </Row>
            <Row>
                <Cell>食べ物</Cell>
                <Cell>Biryani</Cell>
            </Row>
            <Row>
                <Cell>スポーツ</Cell>
                <Cell>Running</Cell>
            </Row>
            <Row>
                <Cell>映画</Cell>
                <Cell>Pulp Fiction</Cell>
            </Row>
            <Row>
                <Cell>本</Cell>
                <Cell>東京ディスニーランドを作った男たち</Cell>
            </Row>
            <Row>
                <Cell>尊敬する人物</Cell>
                <Cell>上岡龍太郎</Cell>
            </Row>
            <Row>
                <Cell>旅行先</Cell>
                <Cell>パリ</Cell>
            </Row>
            <Row>
                <Cell>音楽</Cell>
                <Cell>Soul&Funk</Cell>
            </Row>
            <Row>
                <Cell>科目</Cell>
                <Cell>歴史</Cell>
            </Row>
            <Row>
                <Cell>ペット</Cell>
                <Cell>ネコ</Cell>
            </Row>
            <Row>
                <Cell>マイブーム</Cell>
                <Cell>筋トレ</Cell>
            </Row>
            <Row>
                <Cell>子供の頃の夢</Cell>
                <Cell>教師</Cell>
            </Row>
            <Row>
                <Cell>アプリ</Cell>
                <Cell>X</Cell>
            </Row>
            <Row>
                <Cell>ゲーム</Cell>
                <Cell>ファミコンで終了</Cell>
            </Row>
            <Row>
                <Cell>ストレス発散</Cell>
                <Cell>掃除機かけ</Cell>
            </Row>
            <Row>
                <Cell>スマホ</Cell>
                <Cell>iPhone13</Cell>
            </Row>
            <Row>
                <Cell>色</Cell>
                <Cell>ダーク系</Cell>
            </Row>
            <Row>
                <Cell>物欲</Cell>
                <Cell>なし（ミニマリスト）</Cell>
            </Row>
            <Row>
                <Cell>料理</Cell>
                <Cell>天津飯</Cell>
            </Row>
            <Row>
                <Cell>TV番組</Cell>
                <Cell>イッテQ</Cell>
            </Row>
            <Row>
                <Cell>季節</Cell>
                <Cell>夏</Cell>
            </Row>
            <Row>
                <Cell>幸福</Cell>
                <Cell>自由時間</Cell>
            </Row>
            <Row>
                <Cell>部活</Cell>
                <Cell>バレーボール</Cell>
            </Row>
            <Row>
                <Cell>資格</Cell>
                <Cell>ITストラテジスト</Cell>
            </Row>
            <Row>
                <Cell>場所</Cell>
                <Cell>三重県名張市</Cell>
            </Row>
            <Row>
                <Cell>癒し</Cell>
                <Cell>サウナ</Cell>
            </Row>
            <Row>
                <Cell>お菓子</Cell>
                <Cell>ポテチ</Cell>
            </Row>
            <Row>
                <Cell>交通手段</Cell>
                <Cell>徒歩</Cell>
            </Row>
            <Row>
                <Cell>外国語</Cell>
                <Cell>英語</Cell>
            </Row>
            <Row>
                <Cell>政治</Cell>
                <Cell>無所属</Cell>
            </Row>
            <Row>
                <Cell>ラーメン</Cell>
                <Cell>天一</Cell>
            </Row>
            <Row>
                <Cell>サッカー</Cell>
                <Cell>エスパルス</Cell>
            </Row>
            <Row>
                <Cell>Funk</Cell>
                <Cell>Graham Central Station</Cell>
            </Row>
            <Row>
                <Cell>観光地</Cell>
                <Cell>京都</Cell>
            </Row>
            <Row>
                <Cell>野球</Cell>
                <Cell>阪神</Cell>
            </Row>
            <Row>
                <Cell>コメディ</Cell>
                <Cell>サボテンブラザーズ</Cell>
            </Row>
            <Row>
                <Cell>漫才師</Cell>
                <Cell>中川家</Cell>
            </Row>
            <Row>
                <Cell>PC</Cell>
                <Cell>Macbook Air</Cell>
            </Row>
            <Row>
                <Cell>言語</Cell>
                <Cell>TypeScript</Cell>
            </Row>
            <Row>
                <Cell>ディスニーリゾート</Cell>
                <Cell>シー派</Cell>
            </Row>
            <Row>
                <Cell>Hate</Cell>
                <Cell>渋滞</Cell>
            </Row>
            <Row>
                <Cell>価値観</Cell>
                <Cell>タイパ</Cell>
            </Row>
            <Row>
                <Cell>Komuro系</Cell>
                <Cell>Globe</Cell>
            </Row>
            <Row>
                <Cell>Beatles</Cell>
                <Cell>ForSale</Cell>
            </Row>
            <Row>
                <Cell>キック</Cell>
                <Cell>Left</Cell>
            </Row>
            <Row>
                <Cell>中本</Cell>
                <Cell>北極10倍</Cell>
            </Row>
            <Row>
                <Cell>カレー</Cell>
                <Cell>エチオピア</Cell>
            </Row>
            <Row>
                <Cell>靴</Cell>
                <Cell>amoji</Cell>
            </Row>
        </Body>
    </DataTable>
</div>

<script lang="ts">
    import DataTable, { Head, Body, Row, Cell } from '@smui/data-table';
</script>